sudo: false
dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev

  install:
    - pip3 install codecov
    - pip3 install codacy-coverage
    - pip3 install -e .

  script:
    - pytest -v -s --cov=./

  after_success:
    - codecov -t $CODECOV_PROJECT_TOKEN
    - coverage xml
    - python-codacy-coverage -r coverage.xml

  deploy:
    provider: pypi
    user: mortele
    password: $PYPI_PASSWORD
    on:
      tags: true
      python: 3.7
