sudo: false
dist: xenial
language: python
python:
  - 3.7.1
install:
  - pip3 install -r requirements.txt
script:
  - pytest -v --cov=./
env:
  - CODECOV_TOKEN="a7891cfa-6e25-46f4-a46b-abedaa6a7dfe"
after_success:
  - codecov
